### ISSUE TITLE
move to webxdc org

### ISSUE THREAD

**Issue by hpk42** [deltachat/webxdc_website#4]
i guess we better remove the webxdc.org web page to the webxdc org.

**Comment by Septias** [comment]
Didn't you say, that that organisation is only for webxdc's? @r10s 
But if you also think so, I'll move it over soon

**Comment by r10s** [comment]
we can offer the page as an .xdc ;)

jokes aside, i would not really mind at the end, i am not against the move. there is already a bunch of .xdc in the org, so  the webpage will probably just vanish in the noise :)

**Comment by r10s** [comment]
it is at "Settings" at the very bottom.

however, after some disucssions today, we most likely will not continue doing the site in vue but doing some far more simple for for now, if in doubt, just plain html.  
vue is not very well known among our devs and also seems a bit bloated for a final 10k html page.
so it does not make much sense to move the repo now.

**Comment by Septias** [comment]
Yeah makes sense

**Comment by r10s** [comment]
this issue can be closed by the successor  https://github.com/webxdc/website
